---
title: "ErebiaRepeat"
author: "Marcial Escudero"
date: '2023-02-21'
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(bayou)

tree <- read.nexus("erebia_nondated_phylo.nex")
tree
mydata <- read.table("erebia_dataset.txt")
mydata
row.names(mydata)
setdiff(tree$tip.label, row.names(mydata))
tree <- drop.tip(tree,setdiff(tree$tip.label, row.names(mydata)))
setdiff(tree$tip.label, row.names(mydata))
setdiff(row.names(mydata),tree$tip.label)
names(mydata)

#Chromosome_2N
dat.2n <- as.numeric(mydata[,4])
names(dat.2n) <- row.names(mydata)

priorOU.2n <- make.prior(tree, 
                      dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", 
                                 dk="cdpois", dtheta="dnorm"),
                      param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                 dk=list(lambda=4, kmax=8), dsb=list(bmax=1, prob=1), 
                                 dtheta=list(mean=mean(dat.2n), sd=1.5*sd(dat.2n)))
)





dev.off()
startpars.2n <- priorSim(priorOU.2n, tree, plot=TRUE, cex=0.5)$pars[[1]]




set.seed(1)
mcmcOU.2n <- bayou.makeMCMC(tree, dat.2n, pred = NULL, SE = 0, model = "OU",  priorOU.2n,  samp = 10,  chunk = 100,  control = NULL,  tuning = NULL,  file.dir = tempdir(),  plot.freq = NULL,  outname = "bayou.2n",  plot.fn = phenogram,  ticker.freq = 1000,   startpar = NULL,  moves = NULL, control.weights = NULL, lik.fn = NULL, perform.checks = TRUE)
 # Set up the MCMC
mcmcOU.2n$run(2000000) # Run the MCMC
chainOU.2n <- mcmcOU.2n$load()

chainOU.2n <- set.burnin(chainOU.2n, 0.25)
summary.2n <- summary(chainOU.2n)
par(mfrow=c(3, 5) )
plot(chainOU.2n, auto.layout=FALSE)


dev.off()
plotSimmap.mcmc(chainOU.2n, burnin = 0.25, pp.cutoff = 0.3, cex = 0.5)
plotBranchHeatMap(tree, chainOU.2n, "theta", burnin = 0.25, pal = rainbow, cex = 0.5)
phenogram.density(tree, dat.2n, burnin = 0.25, chainOU.2n, pp.cutoff = 0.3)






#Class_I.DIRS
dat.Class_I.DIRS <- as.numeric(mydata[,5])
names(dat.Class_I.DIRS) <- row.names(mydata)

priorOU.Class_I.DIRS <- make.prior(tree, 
                      dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", 
                                 dk="cdpois", dtheta="dnorm"),
                      param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                 dk=list(lambda=4, kmax=8), dsb=list(bmax=1, prob=1), 
                                 dtheta=list(mean=mean(dat.Class_I.DIRS), sd=1.5*sd(dat.Class_I.DIRS)))
)





dev.off()
startpars.Class_I.DIRS <- priorSim(priorOU.Class_I.DIRS, tree, plot=TRUE, cex=0.5)$pars[[1]]




set.seed(11111)
mcmcOU.Class_I.DIRS <- bayou.makeMCMC(tree, dat.Class_I.DIRS, pred = NULL, SE = 0, model = "OU",  priorOU.Class_I.DIRS,  samp = 10,  chunk = 100,  control = NULL,  tuning = NULL,  file.dir = tempdir(),  plot.freq = NULL,  outname = "bayou.Class_I.DIRS",  plot.fn = phenogram,  ticker.freq = 1000,   startpar = NULL,  moves = NULL, control.weights = NULL, lik.fn = NULL, perform.checks = TRUE)
 # Set up the MCMC
mcmcOU.Class_I.DIRS$run(1000000) # Run the MCMC
chainOU.Class_I.DIRS <- mcmcOU.Class_I.DIRS$load()

chainOU.Class_I.DIRS <- set.burnin(chainOU.Class_I.DIRS, 0.25)
summary.Class_I.DIRS <- summary(chainOU.Class_I.DIRS)
par(mfrow=c(3, 5) )
plot(chainOU.Class_I.DIRS, auto.layout=FALSE)


dev.off()
plotSimmap.mcmc(chainOU.Class_I.DIRS, burnin = 0.25, pp.cutoff = 0.3, cex = 0.5)
plotBranchHeatMap(tree, chainOU.Class_I.DIRS, "theta", burnin = 0.25, pal = rainbow, cex = 0.5)
phenogram.density(tree, dat.Class_I.DIRS, burnin = 0.25, chainOU.Class_I.DIRS, pp.cutoff = 0.3)



#Class_I.LINE
dat.Class_I.LINE <- as.numeric(mydata[,6])
names(dat.Class_I.LINE) <- row.names(mydata)

priorOU.Class_I.LINE <- make.prior(tree, 
                      dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", 
                                 dk="cdpois", dtheta="dnorm"),
                      param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                 dk=list(lambda=4, kmax=8), dsb=list(bmax=1, prob=1), 
                                 dtheta=list(mean=mean(dat.Class_I.LINE), sd=1.5*sd(dat.Class_I.LINE)))
)





dev.off()
startpars.Class_I.LINE <- priorSim(priorOU.Class_I.LINE, tree, plot=TRUE, cex=0.5)$pars[[1]]




set.seed(1)
mcmcOU.Class_I.LINE <- bayou.makeMCMC(tree, dat.Class_I.LINE, pred = NULL, SE = 0, model = "OU",  priorOU.Class_I.LINE,  samp = 10,  chunk = 100,  control = NULL,  tuning = NULL,  file.dir = tempdir(),  plot.freq = NULL,  outname = "bayou.Class_I.LINE",  plot.fn = phenogram,  ticker.freq = 1000,   startpar = NULL,  moves = NULL, control.weights = NULL, lik.fn = NULL, perform.checks = TRUE)
 # Set up the MCMC
mcmcOU.Class_I.LINE$run(1000000) # Run the MCMC
chainOU.Class_I.LINE <- mcmcOU.Class_I.LINE$load()

chainOU.Class_I.LINE <- set.burnin(chainOU.Class_I.LINE, 0.25)
summary.Class_I.LINE <- summary(chainOU.Class_I.LINE)
par(mfrow=c(3, 5) )
plot(chainOU.Class_I.LINE, auto.layout=FALSE)


dev.off()
plotSimmap.mcmc(chainOU.Class_I.LINE, burnin = 0.25, pp.cutoff = 0.3, cex = 0.5,edge.type = "none", edge.color = 1)
plotBranchHeatMap(tree, chainOU.Class_I.LINE, "theta", burnin = 0.25, pal = rainbow, cex = 0.5)
phenogram.density(tree, dat.Class_I.LINE, burnin = 0.25, chainOU.Class_I.LINE, pp.cutoff = 0.3)

#Class_I.LTR
dat.Class_I.LTR <- as.numeric(mydata[,7])
names(dat.Class_I.LTR) <- row.names(mydata)

priorOU.Class_I.LTR <- make.prior(tree, 
                      dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", 
                                 dk="cdpois", dtheta="dnorm"),
                      param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                 dk=list(lambda=4, kmax=8), dsb=list(bmax=1, prob=1), 
                                 dtheta=list(mean=mean(dat.Class_I.LTR), sd=1.5*sd(dat.Class_I.LTR)))
)





dev.off()
startpars.Class_I.LTR <- priorSim(priorOU.Class_I.LTR, tree, plot=TRUE, cex=0.5)$pars[[1]]




set.seed(111)
mcmcOU.Class_I.LTR <- bayou.makeMCMC(tree, dat.Class_I.LTR, pred = NULL, SE = 0, model = "OU",  priorOU.Class_I.LTR,  samp = 10,  chunk = 100,  control = NULL,  tuning = NULL,  file.dir = tempdir(),  plot.freq = NULL,  outname = "bayou.Class_I.LTR",  plot.fn = phenogram,  ticker.freq = 1000,   startpar = NULL,  moves = NULL, control.weights = NULL, lik.fn = NULL, perform.checks = TRUE)
 # Set up the MCMC
mcmcOU.Class_I.LTR$run(2000000) # Run the MCMC
chainOU.Class_I.LTR <- mcmcOU.Class_I.LTR$load()

chainOU.Class_I.LTR <- set.burnin(chainOU.Class_I.LTR, 0.25)
summary.Class_I.LTR <- summary(chainOU.Class_I.LTR)
par(mfrow=c(3, 5) )
plot(chainOU.Class_I.LTR, auto.layout=FALSE)


dev.off()
plotSimmap.mcmc(chainOU.Class_I.LTR, burnin = 0.25, pp.cutoff = 0.3, cex = 0.5)
plotBranchHeatMap(tree, chainOU.Class_I.LTR, "theta", burnin = 0.25, pal = rainbow, cex = 0.5)
phenogram.density(tree, dat.Class_I.LTR, burnin = 0.25, chainOU.Class_I.LTR, pp.cutoff = 0.3)



#Class_I.LTR.Bel.Pao
dat.Class_I.LTR.Bel.Pao <- as.numeric(mydata[,8])
names(dat.Class_I.LTR.Bel.Pao) <- row.names(mydata)

priorOU.Class_I.LTR.Bel.Pao <- make.prior(tree, 
                      dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", 
                                 dk="cdpois", dtheta="dnorm"),
                      param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                 dk=list(lambda=4, kmax=8), dsb=list(bmax=1, prob=1), 
                                 dtheta=list(mean=mean(dat.Class_I.LTR.Bel.Pao), sd=1.5*sd(dat.Class_I.LTR.Bel.Pao)))
)





dev.off()
startpars.Class_I.LTR.Bel.Pao <- priorSim(priorOU.Class_I.LTR.Bel.Pao, tree, plot=TRUE, cex=0.5)$pars[[1]]




set.seed(12221)
mcmcOU.Class_I.LTR.Bel.Pao <- bayou.makeMCMC(tree, dat.Class_I.LTR.Bel.Pao, pred = NULL, SE = 0, model = "OU",  priorOU.Class_I.LTR.Bel.Pao,  samp = 10,  chunk = 100,  control = NULL,  tuning = NULL,  file.dir = tempdir(),  plot.freq = NULL,  outname = "bayou.Class_I.LTR.Bel.Pao",  plot.fn = phenogram,  ticker.freq = 1000,   startpar = NULL,  moves = NULL, control.weights = NULL, lik.fn = NULL, perform.checks = TRUE)
 # Set up the MCMC
mcmcOU.Class_I.LTR.Bel.Pao$run(2000000) # Run the MCMC
chainOU.Class_I.LTR.Bel.Pao <- mcmcOU.Class_I.LTR.Bel.Pao$load()

chainOU.Class_I.LTR.Bel.Pao <- set.burnin(chainOU.Class_I.LTR.Bel.Pao, 0.25)
summary.Class_I.LTR.Bel.Pao <- summary(chainOU.Class_I.LTR.Bel.Pao)
par(mfrow=c(3, 5) )
plot(chainOU.Class_I.LTR.Bel.Pao, auto.layout=FALSE)


dev.off()
plotSimmap.mcmc(chainOU.Class_I.LTR.Bel.Pao, burnin = 0.25, pp.cutoff = 0.3, cex = 0.5)
plotBranchHeatMap(tree, chainOU.Class_I.LTR.Bel.Pao, "theta", burnin = 0.25, pal = rainbow, cex = 0.5)
phenogram.density(tree, dat.Class_I.LTR.Bel.Pao, burnin = 0.25, chainOU.Class_I.LTR.Bel.Pao, pp.cutoff = 0.3)

#Class_I.LTR.Ty1_copia
dat.Class_I.LTR.Ty1_copia <- as.numeric(mydata[,9])
names(dat.Class_I.LTR.Ty1_copia) <- row.names(mydata)

priorOU.Class_I.LTR.Ty1_copia <- make.prior(tree, 
                      dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", 
                                 dk="cdpois", dtheta="dnorm"),
                      param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                 dk=list(lambda=4, kmax=8), dsb=list(bmax=1, prob=1), 
                                 dtheta=list(mean=mean(dat.Class_I.LTR.Ty1_copia), sd=1.5*sd(dat.Class_I.LTR.Ty1_copia)))
)





dev.off()
startpars.Class_I.LTR.Ty1_copia <- priorSim(priorOU.Class_I.LTR.Ty1_copia, tree, plot=TRUE, cex=0.5)$pars[[1]]




set.seed(122)
mcmcOU.Class_I.LTR.Ty1_copia <- bayou.makeMCMC(tree, dat.Class_I.LTR.Ty1_copia, pred = NULL, SE = 0, model = "OU",  priorOU.Class_I.LTR.Ty1_copia,  samp = 10,  chunk = 100,  control = NULL,  tuning = NULL,  file.dir = tempdir(),  plot.freq = NULL,  outname = "bayou.Class_I.LTR.Ty1_copia",  plot.fn = phenogram,  ticker.freq = 1000,   startpar = NULL,  moves = NULL, control.weights = NULL, lik.fn = NULL, perform.checks = TRUE)
 # Set up the MCMC
mcmcOU.Class_I.LTR.Ty1_copia$run(2000000) # Run the MCMC
chainOU.Class_I.LTR.Ty1_copia <- mcmcOU.Class_I.LTR.Ty1_copia$load()

chainOU.Class_I.LTR.Ty1_copia <- set.burnin(chainOU.Class_I.LTR.Ty1_copia, 0.25)
summary.Class_I.LTR.Ty1_copia <- summary(chainOU.Class_I.LTR.Ty1_copia)
par(mfrow=c(3, 5) )
plot(chainOU.Class_I.LTR.Ty1_copia, auto.layout=FALSE)


dev.off()
plotSimmap.mcmc(chainOU.Class_I.LTR.Ty1_copia, burnin = 0.25, pp.cutoff = 0.3, cex = 0.5)
plotBranchHeatMap(tree, chainOU.Class_I.LTR.Ty1_copia, "theta", burnin = 0.25, pal = rainbow, cex = 0.5)
phenogram.density(tree, dat.Class_I.LTR.Ty1_copia, burnin = 0.25, chainOU.Class_I.LTR.Ty1_copia, pp.cutoff = 0.3)


#Class_I.LTR.Ty1_gypsy
dat.Class_I.LTR.Ty1_gypsy <- as.numeric(mydata[,10])
names(dat.Class_I.LTR.Ty1_gypsy) <- row.names(mydata)

priorOU.Class_I.LTR.Ty1_gypsy <- make.prior(tree, 
                      dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", 
                                 dk="cdpois", dtheta="dnorm"),
                      param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                 dk=list(lambda=4, kmax=8), dsb=list(bmax=1, prob=1), 
                                 dtheta=list(mean=mean(dat.Class_I.LTR.Ty1_gypsy), sd=1.5*sd(dat.Class_I.LTR.Ty1_gypsy)))
)





dev.off()
startpars.Class_I.LTR.Ty1_gypsy <- priorSim(priorOU.Class_I.LTR.Ty1_gypsy, tree, plot=TRUE, cex=0.5)$pars[[1]]




set.seed(1)
mcmcOU.Class_I.LTR.Ty1_gypsy <- bayou.makeMCMC(tree, dat.Class_I.LTR.Ty1_gypsy, pred = NULL, SE = 0, model = "OU",  priorOU.Class_I.LTR.Ty1_gypsy,  samp = 10,  chunk = 100,  control = NULL,  tuning = NULL,  file.dir = tempdir(),  plot.freq = NULL,  outname = "bayou.Class_I.LTR.Ty1_gypsy",  plot.fn = phenogram,  ticker.freq = 1000,   startpar = NULL,  moves = NULL, control.weights = NULL, lik.fn = NULL, perform.checks = TRUE)
 # Set up the MCMC
mcmcOU.Class_I.LTR.Ty1_gypsy$run(1000000) # Run the MCMC
chainOU.Class_I.LTR.Ty1_gypsy <- mcmcOU.Class_I.LTR.Ty1_gypsy$load()

chainOU.Class_I.LTR.Ty1_gypsy <- set.burnin(chainOU.Class_I.LTR.Ty1_gypsy, 0.25)
summary.Class_I.LTR.Ty1_gypsy <- summary(chainOU.Class_I.LTR.Ty1_gypsy)
par(mfrow=c(3, 5) )
plot(chainOU.Class_I.LTR.Ty1_gypsy, auto.layout=FALSE)


dev.off()
plotSimmap.mcmc(chainOU.Class_I.LTR.Ty1_gypsy, burnin = 0.25, pp.cutoff = 0.3, cex = 0.5,edge.type = "none", edge.color = 1)
plotBranchHeatMap(tree, chainOU.Class_I.LTR.Ty1_gypsy, "theta", burnin = 0.25, pal = rainbow, cex = 0.5)
phenogram.density(tree, dat.Class_I.LTR.Ty1_gypsy, burnin = 0.25, chainOU.Class_I.LTR.Ty1_gypsy, pp.cutoff = 0.3)



#Class_I.LTR.Ty1_Penelope
dat.Class_I.LTR.Ty1_Penelope <- as.numeric(mydata[,11])
names(dat.Class_I.LTR.Ty1_Penelope) <- row.names(mydata)

priorOU.Class_I.LTR.Ty1_Penelope <- make.prior(tree, 
                      dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", 
                                 dk="cdpois", dtheta="dnorm"),
                      param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                 dk=list(lambda=4, kmax=8), dsb=list(bmax=1, prob=1), 
                                 dtheta=list(mean=mean(dat.Class_I.LTR.Ty1_Penelope), sd=1.5*sd(dat.Class_I.LTR.Ty1_Penelope)))
)





dev.off()
startpars.Class_I.LTR.Ty1_Penelope <- priorSim(priorOU.Class_I.LTR.Ty1_Penelope, tree, plot=TRUE, cex=0.5)$pars[[1]]




set.seed(1)
mcmcOU.Class_I.LTR.Ty1_Penelope <- bayou.makeMCMC(tree, dat.Class_I.LTR.Ty1_Penelope, pred = NULL, SE = 0, model = "OU",  priorOU.Class_I.LTR.Ty1_Penelope,  samp = 10,  chunk = 100,  control = NULL,  tuning = NULL,  file.dir = tempdir(),  plot.freq = NULL,  outname = "bayou.Class_I.LTR.Ty1_Penelope",  plot.fn = phenogram,  ticker.freq = 1000,   startpar = NULL,  moves = NULL, control.weights = NULL, lik.fn = NULL, perform.checks = TRUE)
 # Set up the MCMC
mcmcOU.Class_I.LTR.Ty1_Penelope$run(1000000) # Run the MCMC
chainOU.Class_I.LTR.Ty1_Penelope <- mcmcOU.Class_I.LTR.Ty1_Penelope$load()

chainOU.Class_I.LTR.Ty1_Penelope <- set.burnin(chainOU.Class_I.LTR.Ty1_Penelope, 0.25)
summary.Class_I.LTR.Ty1_Penelope <- summary(chainOU.Class_I.LTR.Ty1_Penelope)
par(mfrow=c(3, 5) )
plot(chainOU.Class_I.LTR.Ty1_Penelope, auto.layout=FALSE)


dev.off()
plotSimmap.mcmc(chainOU.Class_I.LTR.Ty1_Penelope, burnin = 0.25, pp.cutoff = 0.3, cex = 0.5,edge.type = "none", edge.color = 1)
plotBranchHeatMap(tree, chainOU.Class_I.LTR.Ty1_Penelope, "theta", burnin = 0.25, pal = rainbow, cex = 0.5)
phenogram.density(tree, dat.Class_I.LTR.Ty1_Penelope, burnin = 0.25, chainOU.Class_I.LTR.Ty1_Penelope, pp.cutoff = 0.3)



#Class_II.Subclass_2.Helitron
dat.Class_II.Subclass_2.Helitron <- as.numeric(mydata[,12])
names(dat.Class_II.Subclass_2.Helitron) <- row.names(mydata)

priorOU.Class_II.Subclass_2.Helitron <- make.prior(tree, 
                      dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", 
                                 dk="cdpois", dtheta="dnorm"),
                      param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                 dk=list(lambda=4, kmax=8), dsb=list(bmax=1, prob=1), 
                                 dtheta=list(mean=mean(dat.Class_II.Subclass_2.Helitron), sd=1.5*sd(dat.Class_II.Subclass_2.Helitron)))
)





dev.off()
startpars.Class_II.Subclass_2.Helitron <- priorSim(priorOU.Class_II.Subclass_2.Helitron, tree, plot=TRUE, cex=0.5)$pars[[1]]




set.seed(1)
mcmcOU.Class_II.Subclass_2.Helitron <- bayou.makeMCMC(tree, dat.Class_II.Subclass_2.Helitron, pred = NULL, SE = 0, model = "OU",  priorOU.Class_II.Subclass_2.Helitron,  samp = 10,  chunk = 100,  control = NULL,  tuning = NULL,  file.dir = tempdir(),  plot.freq = NULL,  outname = "bayou.Class_II.Subclass_2.Helitron",  plot.fn = phenogram,  ticker.freq = 1000,   startpar = NULL,  moves = NULL, control.weights = NULL, lik.fn = NULL, perform.checks = TRUE)
 # Set up the MCMC
mcmcOU.Class_II.Subclass_2.Helitron$run(3000000) # Run the MCMC
chainOU.Class_II.Subclass_2.Helitron <- mcmcOU.Class_II.Subclass_2.Helitron$load()

chainOU.Class_II.Subclass_2.Helitron <- set.burnin(chainOU.Class_II.Subclass_2.Helitron, 0.25)
summary.Class_II.Subclass_2.Helitron <- summary(chainOU.Class_II.Subclass_2.Helitron)
par(mfrow=c(3, 5) )
plot(chainOU.Class_II.Subclass_2.Helitron, auto.layout=FALSE)


dev.off()
plotSimmap.mcmc(chainOU.Class_II.Subclass_2.Helitron, burnin = 0.25, pp.cutoff = 0.3, cex = 0.5)
plotBranchHeatMap(tree, chainOU.Class_II.Subclass_2.Helitron, "theta", burnin = 0.25, pal = rainbow, cex = 0.5)
phenogram.density(tree, dat.Class_II.Subclass_2.Helitron, burnin = 0.25, chainOU.Class_II.Subclass_2.Helitron, pp.cutoff = 0.3)

#Class_II.Subclass_2.Maverick
dat.Class_II.Subclass_2.Maverick <- as.numeric(mydata[,13])
names(dat.Class_II.Subclass_2.Maverick) <- row.names(mydata)

priorOU.Class_II.Subclass_2.Maverick <- make.prior(tree, 
                      dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", 
                                 dk="cdpois", dtheta="dnorm"),
                      param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                 dk=list(lambda=4, kmax=8), dsb=list(bmax=1, prob=1), 
                                 dtheta=list(mean=mean(dat.Class_II.Subclass_2.Maverick), sd=1.5*sd(dat.Class_II.Subclass_2.Maverick)))
)





dev.off()
startpars.Class_II.Subclass_2.Maverick <- priorSim(priorOU.Class_II.Subclass_2.Maverick, tree, plot=TRUE, cex=0.5)$pars[[1]]




set.seed(1)
mcmcOU.Class_II.Subclass_2.Maverick <- bayou.makeMCMC(tree, dat.Class_II.Subclass_2.Maverick, pred = NULL, SE = 0, model = "OU",  priorOU.Class_II.Subclass_2.Maverick,  samp = 10,  chunk = 100,  control = NULL,  tuning = NULL,  file.dir = tempdir(),  plot.freq = NULL,  outname = "bayou.Class_II.Subclass_2.Maverick",  plot.fn = phenogram,  ticker.freq = 1000,   startpar = NULL,  moves = NULL, control.weights = NULL, lik.fn = NULL, perform.checks = TRUE)
 # Set up the MCMC
mcmcOU.Class_II.Subclass_2.Maverick$run(1000000) # Run the MCMC
chainOU.Class_II.Subclass_2.Maverick <- mcmcOU.Class_II.Subclass_2.Maverick$load()

chainOU.Class_II.Subclass_2.Maverick <- set.burnin(chainOU.Class_II.Subclass_2.Maverick, 0.25)
summary.Class_II.Subclass_2.Maverick <- summary(chainOU.Class_II.Subclass_2.Maverick)
par(mfrow=c(3, 5) )
plot(chainOU.Class_II.Subclass_2.Maverick, auto.layout=FALSE)


dev.off()
plotSimmap.mcmc(chainOU.Class_II.Subclass_2.Maverick, burnin = 0.25, pp.cutoff = 0.3, cex = 0.5,edge.type = "none", edge.color = 1)
plotBranchHeatMap(tree, chainOU.Class_II.Subclass_2.Maverick, "theta", burnin = 0.25, pal = rainbow, cex = 0.5)
phenogram.density(tree, dat.Class_II.Subclass_2.Maverick, burnin = 0.25, chainOU.Class_II.Subclass_2.Maverick, pp.cutoff = 0.3)


#rDNA.45S_rDNA
dat.rDNA.45S_rDNA <- as.numeric(mydata[,14])
names(dat.rDNA.45S_rDNA) <- row.names(mydata)

priorOU.rDNA.45S_rDNA <- make.prior(tree, 
                      dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", 
                                 dk="cdpois", dtheta="dnorm"),
                      param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                 dk=list(lambda=4, kmax=8), dsb=list(bmax=1, prob=1), 
                                 dtheta=list(mean=mean(dat.rDNA.45S_rDNA), sd=1.5*sd(dat.rDNA.45S_rDNA)))
)





dev.off()
startpars.rDNA.45S_rDNA <- priorSim(priorOU.rDNA.45S_rDNA, tree, plot=TRUE, cex=0.5)$pars[[1]]




set.seed(1)
mcmcOU.rDNA.45S_rDNA <- bayou.makeMCMC(tree, dat.rDNA.45S_rDNA, pred = NULL, SE = 0, model = "OU",  priorOU.rDNA.45S_rDNA,  samp = 10,  chunk = 100,  control = NULL,  tuning = NULL,  file.dir = tempdir(),  plot.freq = NULL,  outname = "bayou.rDNA.45S_rDNA",  plot.fn = phenogram,  ticker.freq = 1000,   startpar = NULL,  moves = NULL, control.weights = NULL, lik.fn = NULL, perform.checks = TRUE)
 # Set up the MCMC
mcmcOU.rDNA.45S_rDNA$run(2000000) # Run the MCMC
chainOU.rDNA.45S_rDNA <- mcmcOU.rDNA.45S_rDNA$load()

chainOU.rDNA.45S_rDNA <- set.burnin(chainOU.rDNA.45S_rDNA, 0.25)
summary.rDNA.45S_rDNA <- summary(chainOU.rDNA.45S_rDNA)
par(mfrow=c(3, 5) )
plot(chainOU.rDNA.45S_rDNA, auto.layout=FALSE)


dev.off()
plotSimmap.mcmc(chainOU.rDNA.45S_rDNA, burnin = 0.25, pp.cutoff = 0.3, cex = 0.5)
plotBranchHeatMap(tree, chainOU.rDNA.45S_rDNA, "theta", burnin = 0.25, pal = rainbow, cex = 0.5)
phenogram.density(tree, dat.rDNA.45S_rDNA, burnin = 0.25, chainOU.rDNA.45S_rDNA, pp.cutoff = 0.3)


#satellite
dat.satellite <- as.numeric(mydata[,15])
names(dat.satellite) <- row.names(mydata)

priorOU.satellite <- make.prior(tree, 
                      dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", 
                                 dk="cdpois", dtheta="dnorm"),
                      param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                 dk=list(lambda=4, kmax=8), dsb=list(bmax=1, prob=1), 
                                 dtheta=list(mean=mean(dat.satellite), sd=1.5*sd(dat.satellite)))
)





dev.off()
startpars.satellite <- priorSim(priorOU.satellite, tree, plot=TRUE, cex=0.5)$pars[[1]]




set.seed(7)
mcmcOU.satellite <- bayou.makeMCMC(tree, dat.satellite, pred = NULL, SE = 0, model = "OU",  priorOU.satellite,  samp = 10,  chunk = 100,  control = NULL,  tuning = NULL,  file.dir = tempdir(),  plot.freq = NULL,  outname = "bayou.satellite",  plot.fn = phenogram,  ticker.freq = 1000,   startpar = NULL,  moves = NULL, control.weights = NULL, lik.fn = NULL, perform.checks = TRUE)
 # Set up the MCMC
mcmcOU.satellite$run(2000000) # Run the MCMC
chainOU.satellite <- mcmcOU.satellite$load()

chainOU.satellite <- set.burnin(chainOU.satellite, 0.25)
summary.satellite <- summary(chainOU.satellite)
par(mfrow=c(3, 5) )
plot(chainOU.satellite, auto.layout=FALSE)


dev.off()
plotSimmap.mcmc(chainOU.satellite, burnin = 0.25, pp.cutoff = 0.3, cex = 0.5)
plotBranchHeatMap(tree, chainOU.satellite, "theta", burnin = 0.25, pal = rainbow, cex = 0.5)
phenogram.density(tree, dat.satellite, burnin = 0.25, chainOU.satellite, pp.cutoff = 0.3)

```



```{r}
library(bayou)

tree <- read.nexus("erebia_nondated_phylo.nex")
tree
mydata <- read.table("erebia_dataset.txt")
mydata
row.names(mydata)
setdiff(tree$tip.label, row.names(mydata))
tree <- drop.tip(tree,setdiff(tree$tip.label, row.names(mydata)))


#Class_II.Subclass_2.Helitron

prior.11.Class_II.Subclass_2.Helitron <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_II.Subclass_2.Helitron="dnorm",
                                  dsb="fixed", dk="fixed", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_II.Subclass_2.Helitron=list(mean=0.7, sd=0.15),
                                  dtheta=list(mean=0, sd=1)),
                       fixed=list(k=0, sb=numeric(0))
)

prior.N1.Class_II.Subclass_2.Helitron <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_II.Subclass_2.Helitron="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dbeta_Class_II.Subclass_2.Helitron=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50),
                                  dtheta=list(mean=0, sd=1))
)


prior.NN.Class_II.Subclass_2.Helitron <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_II.Subclass_2.Helitron="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_II.Subclass_2.Helitron=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50), 
                                  dtheta=list(mean=0, sd=1))
)


D11.Class_II.Subclass_2.Helitron = list(alpha=2, sig2=2, beta_Class_II.Subclass_2.Helitron=0.1, k=1, theta=0.5, slide=1)
DN1.Class_II.Subclass_2.Helitron = list(alpha=2, sig2=2, beta_Class_II.Subclass_2.Helitron=0.1, k=1, theta=2, slide=1)
DNN.Class_II.Subclass_2.Helitron = list(alpha=2, sig2=2, beta_Class_II.Subclass_2.Helitron=0.3, k=c(1,1), theta=2, slide=1)

pred.Class_II.Subclass_2.Helitron <- as.numeric(mydata[,12])
dim(pred.Class_II.Subclass_2.Helitron) <- c(47,1)
row.names(pred.Class_II.Subclass_2.Helitron) <- row.names(mydata)
pred.Class_II.Subclass_2.Helitron
colnames(pred.Class_II.Subclass_2.Helitron) <- c("Class_II.Subclass_2.Helitron")

set.seed(1111111)
model.11.Class_II.Subclass_2.Helitron <- makeBayouModel(dat.2n ~ Class_II.Subclass_2.Helitron, rjpars = c(), 
                           tree=tree, dat=dat.2n, pred=pred.Class_II.Subclass_2.Helitron, SE=0, prior=prior.11.Class_II.Subclass_2.Helitron, D=D11.Class_II.Subclass_2.Helitron)
model.N1.Class_II.Subclass_2.Helitron <- makeBayouModel(dat.2n ~ Class_II.Subclass_2.Helitron, rjpars = c("theta"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_II.Subclass_2.Helitron, SE=0, prior=prior.N1.Class_II.Subclass_2.Helitron, D=DN1.Class_II.Subclass_2.Helitron)
model.NN.Class_II.Subclass_2.Helitron <- makeBayouModel(dat.2n ~ Class_II.Subclass_2.Helitron, rjpars = c("theta", "Class_II.Subclass_2.Helitron"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_II.Subclass_2.Helitron, SE=0, prior=prior.NN.Class_II.Subclass_2.Helitron, D=DNN.Class_II.Subclass_2.Helitron)

mcmc.11.Class_II.Subclass_2.Helitron <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_II.Subclass_2.Helitron, SE=0, model=model.11.Class_II.Subclass_2.Helitron$model, prior=prior.11.Class_II.Subclass_2.Helitron, startpar=model.11.Class_II.Subclass_2.Helitron$startpar, outname="model11_r001_Class_II.Subclass_2.Helitron", plot.freq=NULL)
mcmc.N1.Class_II.Subclass_2.Helitron <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_II.Subclass_2.Helitron, SE=0, model=model.N1.Class_II.Subclass_2.Helitron$model, prior=prior.N1.Class_II.Subclass_2.Helitron, startpar=model.N1.Class_II.Subclass_2.Helitron$startpar, outname="modelN1_r001_Class_II.Subclass_2.Helitron", plot.freq=NULL)
mcmc.NN.Class_II.Subclass_2.Helitron <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_II.Subclass_2.Helitron, SE=0, model=model.NN.Class_II.Subclass_2.Helitron$model, prior=prior.NN.Class_II.Subclass_2.Helitron, startpar=model.NN.Class_II.Subclass_2.Helitron$startpar, outname="modelNN_r001_Class_II.Subclass_2.Helitron", plot.freq=NULL)

set.seed(1)
mcmc.11.Class_II.Subclass_2.Helitron$run(1000000)
mcmc.N1.Class_II.Subclass_2.Helitron$run(1000000)
mcmc.NN.Class_II.Subclass_2.Helitron$run(1000000)

chain.11.Class_II.Subclass_2.Helitron <- set.burnin(mcmc.11.Class_II.Subclass_2.Helitron$load(), 0.3)
chain.N1.Class_II.Subclass_2.Helitron <- set.burnin(mcmc.N1.Class_II.Subclass_2.Helitron$load(), 0.3)
chain.NN.Class_II.Subclass_2.Helitron <- set.burnin(mcmc.NN.Class_II.Subclass_2.Helitron$load(), 0.3)

shiftsumsN1.Class_II.Subclass_2.Helitron <- shiftSummaries(chain.N1.Class_II.Subclass_2.Helitron, mcmc.N1.Class_II.Subclass_2.Helitron, pp.cutoff=0.17)
shiftsumsNN.Class_II.Subclass_2.Helitron <- shiftSummaries(chain.NN.Class_II.Subclass_2.Helitron, mcmc.NN.Class_II.Subclass_2.Helitron, pp.cutoff=0.3)

plotShiftSummaries(shiftsumsN1.Class_II.Subclass_2.Helitron, lwd=2, single.plot=TRUE, label.pts=FALSE)
plotShiftSummaries(shiftsumsNN.Class_II.Subclass_2.Helitron, lwd=2, single.plot=TRUE, label.pts=FALSE)

Bk <- qbeta(seq(0,1, length.out=5), 0.3,1)
set.seed(1)
ss.11.Class_II.Subclass_2.Helitron <- mcmc.11.Class_II.Subclass_2.Helitron$steppingstone(10000, chain.11.Class_II.Subclass_2.Helitron, Bk, burnin=0.3, plot=FALSE)
ss.N1.Class_II.Subclass_2.Helitron <- mcmc.N1.Class_II.Subclass_2.Helitron$steppingstone(10000, chain.N1.Class_II.Subclass_2.Helitron, Bk, burnin=0.3, plot=FALSE)
ss.NN.Class_II.Subclass_2.Helitron <- mcmc.NN.Class_II.Subclass_2.Helitron$steppingstone(10000, chain.NN.Class_II.Subclass_2.Helitron, Bk, burnin=0.3, plot=FALSE)

mlnL.Class_II.Subclass_2.Helitron <- c("11"=ss.11.Class_II.Subclass_2.Helitron$lnr, "N1"=ss.N1.Class_II.Subclass_2.Helitron$lnr, "NN"=ss.NN.Class_II.Subclass_2.Helitron$lnr)
mlnL.Class_II.Subclass_2.Helitron


summary.N1.Class_II.Subclass_2.Helitron <- summary(chain.N1.Class_II.Subclass_2.Helitron)
#par(mfrow=c(3, 5) )
#plot(chain.NN.Class_II.Subclass_2.Helitron, auto.layout=FALSE)


#dev.off()
#plotSimmap.mcmc(chain.N1.rDNA.45S_rDNA, burnin = 0.3, pp.cutoff = 0.17, cex = 0.5)

#Class_I.DIRS
prior.11.Class_I.DIRS <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.DIRS="dnorm",
                                  dsb="fixed", dk="fixed", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_I.DIRS=list(mean=0.7, sd=0.15),
                                  dtheta=list(mean=0, sd=1)),
                       fixed=list(k=0, sb=numeric(0))
)

prior.N1.Class_I.DIRS <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.DIRS="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dbeta_Class_I.DIRS=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50),
                                  dtheta=list(mean=0, sd=1))
)


prior.NN.Class_I.DIRS <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.DIRS="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_I.DIRS=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50), 
                                  dtheta=list(mean=0, sd=1))
)


D11.Class_I.DIRS = list(alpha=2, sig2=2, beta_Class_I.DIRS=0.1, k=1, theta=0.5, slide=1)
DN1.Class_I.DIRS = list(alpha=2, sig2=2, beta_Class_I.DIRS=0.1, k=1, theta=2, slide=1)
DNN.Class_I.DIRS = list(alpha=2, sig2=2, beta_Class_I.DIRS=0.3, k=c(1,1), theta=2, slide=1)

pred.Class_I.DIRS <- as.numeric(mydata[,5])
dim(pred.Class_I.DIRS) <- c(47,1)
row.names(pred.Class_I.DIRS) <- row.names(mydata)
pred.Class_I.DIRS
colnames(pred.Class_I.DIRS) <- c("Class_I.DIRS")

set.seed(1111111)
model.11.Class_I.DIRS <- makeBayouModel(dat.2n ~ Class_I.DIRS, rjpars = c(), 
                           tree=tree, dat=dat.2n, pred=pred.Class_I.DIRS, SE=0, prior=prior.11.Class_I.DIRS, D=D11.Class_I.DIRS)
model.N1.Class_I.DIRS <- makeBayouModel(dat.2n ~ Class_I.DIRS, rjpars = c("theta"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_I.DIRS, SE=0, prior=prior.N1.Class_I.DIRS, D=DN1.Class_I.DIRS)
model.NN.Class_I.DIRS <- makeBayouModel(dat.2n ~ Class_I.DIRS, rjpars = c("theta", "Class_I.DIRS"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_I.DIRS, SE=0, prior=prior.NN.Class_I.DIRS, D=DNN.Class_I.DIRS)

mcmc.11.Class_I.DIRS <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.DIRS, SE=0, model=model.11.Class_I.DIRS$model, prior=prior.11.Class_I.DIRS, startpar=model.11.Class_I.DIRS$startpar, outname="model11_r001_Class_I.DIRS", plot.freq=NULL)
mcmc.N1.Class_I.DIRS <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.DIRS, SE=0, model=model.N1.Class_I.DIRS$model, prior=prior.N1.Class_I.DIRS, startpar=model.N1.Class_I.DIRS$startpar, outname="modelN1_r001_Class_I.DIRS", plot.freq=NULL)
mcmc.NN.Class_I.DIRS <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.DIRS, SE=0, model=model.NN.Class_I.DIRS$model, prior=prior.NN.Class_I.DIRS, startpar=model.NN.Class_I.DIRS$startpar, outname="modelNN_r001_Class_I.DIRS", plot.freq=NULL)

set.seed(1)
mcmc.11.Class_I.DIRS$run(1000000)
mcmc.N1.Class_I.DIRS$run(1000000)
mcmc.NN.Class_I.DIRS$run(1000000)

chain.11.Class_I.DIRS <- set.burnin(mcmc.11.Class_I.DIRS$load(), 0.3)
chain.N1.Class_I.DIRS <- set.burnin(mcmc.N1.Class_I.DIRS$load(), 0.3)
chain.NN.Class_I.DIRS <- set.burnin(mcmc.NN.Class_I.DIRS$load(), 0.3)

shiftsumsN1.Class_I.DIRS <- shiftSummaries(chain.N1.Class_I.DIRS, mcmc.N1.Class_I.DIRS, pp.cutoff=0.168)
shiftsumsNN.Class_I.DIRS <- shiftSummaries(chain.NN.Class_I.DIRS, mcmc.NN.Class_I.DIRS, pp.cutoff=0.3)

plotShiftSummaries(shiftsumsN1.Class_I.DIRS, lwd=2, single.plot=TRUE, label.pts=FALSE)
plotShiftSummaries(shiftsumsNN.Class_I.DIRS, lwd=2, single.plot=TRUE, label.pts=FALSE)

Bk <- qbeta(seq(0,1, length.out=5), 0.3,1)
set.seed(1)
ss.11.Class_I.DIRS <- mcmc.11.Class_I.DIRS$steppingstone(10000, chain.11.Class_I.DIRS, Bk, burnin=0.3, plot=FALSE)
ss.N1.Class_I.DIRS <- mcmc.N1.Class_I.DIRS$steppingstone(10000, chain.N1.Class_I.DIRS, Bk, burnin=0.3, plot=FALSE)
ss.NN.Class_I.DIRS <- mcmc.NN.Class_I.DIRS$steppingstone(10000, chain.NN.Class_I.DIRS, Bk, burnin=0.3, plot=FALSE)

mlnL.Class_I.DIRS <- c("11"=ss.11.Class_I.DIRS$lnr, "N1"=ss.N1.Class_I.DIRS$lnr, "NN"=ss.NN.Class_I.DIRS$lnr)
mlnL.Class_I.DIRS


summary.N1.Class_I.DIRS <- summary(chain.N1.Class_I.DIRS)
#par(mfrow=c(3, 5) )
#plot(chain.NN.Class_I.DIRS, auto.layout=FALSE)


#dev.off()
#plotSimmap.mcmc(chain.N1.Class_I.DIRS, burnin = 0.3, pp.cutoff = 0.169, cex = 0.5)



#Class_I.LTR
prior.11.Class_I.LTR <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LTR="dnorm",
                                  dsb="fixed", dk="fixed", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_I.LTR=list(mean=0.7, sd=0.15),
                                  dtheta=list(mean=0, sd=1)),
                       fixed=list(k=0, sb=numeric(0))
)

prior.N1.Class_I.LTR <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LTR="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dbeta_Class_I.LTR=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50),
                                  dtheta=list(mean=0, sd=1))
)


prior.NN.Class_I.LTR <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LTR="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_I.LTR=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50), 
                                  dtheta=list(mean=0, sd=1))
)


D11.Class_I.LTR = list(alpha=2, sig2=2, beta_Class_I.LTR=0.1, k=1, theta=0.5, slide=1)
DN1.Class_I.LTR = list(alpha=2, sig2=2, beta_Class_I.LTR=0.1, k=1, theta=2, slide=1)
DNN.Class_I.LTR = list(alpha=2, sig2=2, beta_Class_I.LTR=0.3, k=c(1,1), theta=2, slide=1)

pred.Class_I.LTR <- as.numeric(mydata[,7])
dim(pred.Class_I.LTR) <- c(47,1)
row.names(pred.Class_I.LTR) <- row.names(mydata)
pred.Class_I.LTR
colnames(pred.Class_I.LTR) <- c("Class_I.LTR")

set.seed(1)
model.11.Class_I.LTR <- makeBayouModel(dat.2n ~ Class_I.LTR, rjpars = c(), 
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LTR, SE=0, prior=prior.11.Class_I.LTR, D=D11.Class_I.LTR)
model.N1.Class_I.LTR <- makeBayouModel(dat.2n ~ Class_I.LTR, rjpars = c("theta"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LTR, SE=0, prior=prior.N1.Class_I.LTR, D=DN1.Class_I.LTR)
model.NN.Class_I.LTR <- makeBayouModel(dat.2n ~ Class_I.LTR, rjpars = c("theta", "Class_I.LTR"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LTR, SE=0, prior=prior.NN.Class_I.LTR, D=DNN.Class_I.LTR)

mcmc.11.Class_I.LTR <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LTR, SE=0, model=model.11.Class_I.LTR$model, prior=prior.11.Class_I.LTR, startpar=model.11.Class_I.LTR$startpar, outname="model11_r001_Class_I.LTR", plot.freq=NULL)
mcmc.N1.Class_I.LTR <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LTR, SE=0, model=model.N1.Class_I.LTR$model, prior=prior.N1.Class_I.LTR, startpar=model.N1.Class_I.LTR$startpar, outname="modelN1_r001_Class_I.LTR", plot.freq=NULL)
mcmc.NN.Class_I.LTR <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LTR, SE=0, model=model.NN.Class_I.LTR$model, prior=prior.NN.Class_I.LTR, startpar=model.NN.Class_I.LTR$startpar, outname="modelNN_r001_Class_I.LTR", plot.freq=NULL)

set.seed(111)
mcmc.11.Class_I.LTR$run(1000000)
mcmc.N1.Class_I.LTR$run(1000000)
mcmc.NN.Class_I.LTR$run(1000000)

chain.11.Class_I.LTR <- set.burnin(mcmc.11.Class_I.LTR$load(), 0.3)
chain.N1.Class_I.LTR <- set.burnin(mcmc.N1.Class_I.LTR$load(), 0.3)
chain.NN.Class_I.LTR <- set.burnin(mcmc.NN.Class_I.LTR$load(), 0.3)

shiftsumsN1.Class_I.LTR <- shiftSummaries(chain.N1.Class_I.LTR, mcmc.N1.Class_I.LTR, pp.cutoff=0.3)
shiftsumsNN.Class_I.LTR <- shiftSummaries(chain.NN.Class_I.LTR, mcmc.NN.Class_I.LTR, pp.cutoff=0.3)

plotShiftSummaries(shiftsumsN1.Class_I.LTR, lwd=2, single.plot=TRUE, label.pts=FALSE)
plotShiftSummaries(shiftsumsNN.Class_I.LTR, lwd=2, single.plot=TRUE, label.pts=FALSE)

Bk <- qbeta(seq(0,1, length.out=5), 0.3,1)
set.seed(1111)
ss.11.Class_I.LTR <- mcmc.11.Class_I.LTR$steppingstone(10000, chain.11.Class_I.LTR, Bk, burnin=0.3, plot=FALSE)
ss.N1.Class_I.LTR <- mcmc.N1.Class_I.LTR$steppingstone(10000, chain.N1.Class_I.LTR, Bk, burnin=0.3, plot=FALSE)
ss.NN.Class_I.LTR <- mcmc.NN.Class_I.LTR$steppingstone(10000, chain.NN.Class_I.LTR, Bk, burnin=0.3, plot=FALSE)

mlnL.Class_I.LTR <- c("11"=ss.11.Class_I.LTR$lnr, "N1"=ss.N1.Class_I.LTR$lnr, "NN"=ss.NN.Class_I.LTR$lnr)
mlnL.Class_I.LTR


summary.NN.Class_I.DIRS <- summary(chain.NN.Class_I.LTR)
#par(mfrow=c(3, 5) )
#plot(chain.NN.Class_I.LTR, auto.layout=FALSE)


#dev.off()
plotSimmap.mcmc(chain.NN.Class_I.LTR, burnin = 0.3, pp.cutoff = 0.3, cex = 0.5)





#rDNA.45S_rDNA

prior.11.rDNA.45S_rDNA <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_rDNA.45S_rDNA="dnorm",
                                  dsb="fixed", dk="fixed", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_rDNA.45S_rDNA=list(mean=0.7, sd=0.15),
                                  dtheta=list(mean=0, sd=1)),
                       fixed=list(k=0, sb=numeric(0))
)

prior.N1.rDNA.45S_rDNA <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_rDNA.45S_rDNA="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dbeta_rDNA.45S_rDNA=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50),
                                  dtheta=list(mean=0, sd=1))
)


prior.NN.rDNA.45S_rDNA <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_rDNA.45S_rDNA="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_rDNA.45S_rDNA=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50), 
                                  dtheta=list(mean=0, sd=1))
)


D11.rDNA.45S_rDNA = list(alpha=2, sig2=2, beta_rDNA.45S_rDNA=0.1, k=1, theta=0.5, slide=1)
DN1.rDNA.45S_rDNA = list(alpha=2, sig2=2, beta_rDNA.45S_rDNA=0.1, k=1, theta=2, slide=1)
DNN.rDNA.45S_rDNA = list(alpha=2, sig2=2, beta_rDNA.45S_rDNA=0.3, k=c(1,1), theta=2, slide=1)

pred.rDNA.45S_rDNA <- as.numeric(mydata[,14])
dim(pred.rDNA.45S_rDNA) <- c(47,1)
row.names(pred.rDNA.45S_rDNA) <- row.names(mydata)
pred.rDNA.45S_rDNA
colnames(pred.rDNA.45S_rDNA) <- c("rDNA.45S_rDNA")

set.seed(111111)
model.11.rDNA.45S_rDNA <- makeBayouModel(dat.2n ~ rDNA.45S_rDNA, rjpars = c(), 
                           tree=tree, dat=dat.2n, pred=pred.rDNA.45S_rDNA, SE=0, prior=prior.11.rDNA.45S_rDNA, D=D11.rDNA.45S_rDNA)
model.N1.rDNA.45S_rDNA <- makeBayouModel(dat.2n ~ rDNA.45S_rDNA, rjpars = c("theta"),  
                           tree=tree, dat=dat.2n, pred=pred.rDNA.45S_rDNA, SE=0, prior=prior.N1.rDNA.45S_rDNA, D=DN1.rDNA.45S_rDNA)
model.NN.rDNA.45S_rDNA <- makeBayouModel(dat.2n ~ rDNA.45S_rDNA, rjpars = c("theta", "rDNA.45S_rDNA"),  
                           tree=tree, dat=dat.2n, pred=pred.rDNA.45S_rDNA, SE=0, prior=prior.NN.rDNA.45S_rDNA, D=DNN.rDNA.45S_rDNA)

mcmc.11.rDNA.45S_rDNA <- bayou.makeMCMC(tree, dat.2n, pred=pred.rDNA.45S_rDNA, SE=0, model=model.11.rDNA.45S_rDNA$model, prior=prior.11.rDNA.45S_rDNA, startpar=model.11.rDNA.45S_rDNA$startpar, outname="model11_r001_rDNA.45S_rDNA", plot.freq=NULL)
mcmc.N1.rDNA.45S_rDNA <- bayou.makeMCMC(tree, dat.2n, pred=pred.rDNA.45S_rDNA, SE=0, model=model.N1.rDNA.45S_rDNA$model, prior=prior.N1.rDNA.45S_rDNA, startpar=model.N1.rDNA.45S_rDNA$startpar, outname="modelN1_r001_rDNA.45S_rDNA", plot.freq=NULL)
mcmc.NN.rDNA.45S_rDNA <- bayou.makeMCMC(tree, dat.2n, pred=pred.rDNA.45S_rDNA, SE=0, model=model.NN.rDNA.45S_rDNA$model, prior=prior.NN.rDNA.45S_rDNA, startpar=model.NN.rDNA.45S_rDNA$startpar, outname="modelNN_r001_rDNA.45S_rDNA", plot.freq=NULL)

set.seed(1)
mcmc.11.rDNA.45S_rDNA$run(1000000)
mcmc.N1.rDNA.45S_rDNA$run(1000000)
mcmc.NN.rDNA.45S_rDNA$run(1000000)

chain.11.rDNA.45S_rDNA <- set.burnin(mcmc.11.rDNA.45S_rDNA$load(), 0.3)
chain.N1.rDNA.45S_rDNA <- set.burnin(mcmc.N1.rDNA.45S_rDNA$load(), 0.3)
chain.NN.rDNA.45S_rDNA <- set.burnin(mcmc.NN.rDNA.45S_rDNA$load(), 0.3)

shiftsumsN1.rDNA.45S_rDNA <- shiftSummaries(chain.N1.rDNA.45S_rDNA, mcmc.N1.rDNA.45S_rDNA, pp.cutoff=0.17)
shiftsumsNN.rDNA.45S_rDNA <- shiftSummaries(chain.NN.rDNA.45S_rDNA, mcmc.NN.rDNA.45S_rDNA, pp.cutoff=0.3)

plotShiftSummaries(shiftsumsNN., lwd=2, single.plot=TRUE, label.pts=FALSE)
plotShiftSummaries(shiftsumsNN.rDNA.45S_rDNA, lwd=2, single.plot=TRUE, label.pts=FALSE)

Bk <- qbeta(seq(0,1, length.out=5), 0.3,1)
set.seed(1)
ss.11.rDNA.45S_rDNA <- mcmc.11.rDNA.45S_rDNA$steppingstone(10000, chain.11.rDNA.45S_rDNA, Bk, burnin=0.3, plot=FALSE)
ss.N1.rDNA.45S_rDNA <- mcmc.N1.rDNA.45S_rDNA$steppingstone(10000, chain.N1.rDNA.45S_rDNA, Bk, burnin=0.3, plot=FALSE)
ss.NN.rDNA.45S_rDNA <- mcmc.NN.rDNA.45S_rDNA$steppingstone(10000, chain.NN.rDNA.45S_rDNA, Bk, burnin=0.3, plot=FALSE)

mlnL.rDNA.45S_rDNA <- c("11"=ss.11.rDNA.45S_rDNA$lnr, "N1"=ss.N1.rDNA.45S_rDNA$lnr, "NN"=ss.NN.rDNA.45S_rDNA$lnr)
mlnL.rDNA.45S_rDNA


summary.N1.rDNA.45S_rDNA <- summary(chain.N1.rDNA.45S_rDNA)
#par(mfrow=c(3, 5) )
#plot(chain.NN.rDNA.45S_rDNA, auto.layout=FALSE)


#dev.off()
#plotSimmap.mcmc(chain.N1.rDNA.45S_rDNA, burnin = 0.3, pp.cutoff = 0.17, cex = 0.5)



#satellite

prior.11.satellite <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_satellite="dnorm",
                                  dsb="fixed", dk="fixed", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_satellite=list(mean=0.7, sd=0.15),
                                  dtheta=list(mean=0, sd=1)),
                       fixed=list(k=0, sb=numeric(0))
)

prior.N1.satellite <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_satellite="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dbeta_satellite=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50),
                                  dtheta=list(mean=0, sd=1))
)


prior.NN.satellite <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_satellite="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_satellite=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50), 
                                  dtheta=list(mean=0, sd=1))
)


D11.satellite = list(alpha=2, sig2=2, beta_satellite=0.1, k=1, theta=0.5, slide=1)
DN1.satellite = list(alpha=2, sig2=2, beta_satellite=0.1, k=1, theta=2, slide=1)
DNN.satellite = list(alpha=2, sig2=2, beta_satellite=0.3, k=c(1,1), theta=2, slide=1)

pred.satellite <- as.numeric(mydata[,15])
dim(pred.satellite) <- c(47,1)
row.names(pred.satellite) <- row.names(mydata)
pred.satellite
colnames(pred.satellite) <- c("satellite")

set.seed(111111)
model.11.satellite <- makeBayouModel(dat.2n ~ satellite, rjpars = c(), 
                           tree=tree, dat=dat.2n, pred=pred.satellite, SE=0, prior=prior.11.satellite, D=D11.satellite)
model.N1.satellite <- makeBayouModel(dat.2n ~ satellite, rjpars = c("theta"),  
                           tree=tree, dat=dat.2n, pred=pred.satellite, SE=0, prior=prior.N1.satellite, D=DN1.satellite)
model.NN.satellite <- makeBayouModel(dat.2n ~ satellite, rjpars = c("theta", "satellite"),  
                           tree=tree, dat=dat.2n, pred=pred.satellite, SE=0, prior=prior.NN.satellite, D=DNN.satellite)

mcmc.11.satellite <- bayou.makeMCMC(tree, dat.2n, pred=pred.satellite, SE=0, model=model.11.satellite$model, prior=prior.11.satellite, startpar=model.11.satellite$startpar, outname="model11_r001_satellite", plot.freq=NULL)
mcmc.N1.satellite <- bayou.makeMCMC(tree, dat.2n, pred=pred.satellite, SE=0, model=model.N1.satellite$model, prior=prior.N1.satellite, startpar=model.N1.satellite$startpar, outname="modelN1_r001_satellite", plot.freq=NULL)
mcmc.NN.satellite <- bayou.makeMCMC(tree, dat.2n, pred=pred.satellite, SE=0, model=model.NN.satellite$model, prior=prior.NN.satellite, startpar=model.NN.satellite$startpar, outname="modelNN_r001_satellite", plot.freq=NULL)

set.seed(1)
mcmc.11.satellite$run(1000000)
mcmc.N1.satellite$run(1000000)
mcmc.NN.satellite$run(1000000)

chain.11.satellite <- set.burnin(mcmc.11.satellite$load(), 0.3)
chain.N1.satellite <- set.burnin(mcmc.N1.satellite$load(), 0.3)
chain.NN.satellite <- set.burnin(mcmc.NN.satellite$load(), 0.3)

shiftsumsN1.satellite <- shiftSummaries(chain.N1.satellite, mcmc.N1.satellite, pp.cutoff=0.17)
shiftsumsNN.satellite <- shiftSummaries(chain.NN.satellite, mcmc.NN.satellite, pp.cutoff=0.3)

plotShiftSummaries(shiftsumsN1.satellite, lwd=2, single.plot=TRUE, label.pts=FALSE)
plotShiftSummaries(shiftsumsNN.satellite, lwd=2, single.plot=TRUE, label.pts=FALSE)

Bk <- qbeta(seq(0,1, length.out=5), 0.3,1)
set.seed(1)
ss.11.satellite <- mcmc.11.satellite$steppingstone(10000, chain.11.satellite, Bk, burnin=0.3, plot=FALSE)
ss.N1.satellite <- mcmc.N1.satellite$steppingstone(10000, chain.N1.satellite, Bk, burnin=0.3, plot=FALSE)
ss.NN.satellite <- mcmc.NN.satellite$steppingstone(10000, chain.NN.satellite, Bk, burnin=0.3, plot=FALSE)

mlnL.satellite <- c("11"=ss.11.satellite$lnr, "N1"=ss.N1.satellite$lnr, "NN"=ss.NN.satellite$lnr)
mlnL.satellite


summary.N1.satellite <- summary(chain.N1.satellite)
#par(mfrow=c(3, 5) )
#plot(chain.NN.satellite, auto.layout=FALSE)


#dev.off()
#plotSimmap.mcmc(chain.N1.satellite, burnin = 0.3, pp.cutoff = 0.17, cex = 0.5)



#Class_I.LINE

prior.11.Class_I.LINE <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LINE="dnorm",
                                  dsb="fixed", dk="fixed", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_I.LINE=list(mean=0.7, sd=0.15),
                                  dtheta=list(mean=0, sd=1)),
                       fixed=list(k=0, sb=numeric(0))
)

prior.N1.Class_I.LINE <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LINE="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dbeta_Class_I.LINE=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50),
                                  dtheta=list(mean=0, sd=1))
)


prior.NN.Class_I.LINE <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LINE="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_I.LINE=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50), 
                                  dtheta=list(mean=0, sd=1))
)


D11.Class_I.LINE = list(alpha=2, sig2=2, beta_Class_I.LINE=0.1, k=1, theta=0.5, slide=1)
DN1.Class_I.LINE = list(alpha=2, sig2=2, beta_Class_I.LINE=0.1, k=1, theta=2, slide=1)
DNN.Class_I.LINE = list(alpha=2, sig2=2, beta_Class_I.LINE=0.3, k=c(1,1), theta=2, slide=1)

pred.Class_I.LINE <- as.numeric(mydata[,6])
dim(pred.Class_I.LINE) <- c(47,1)
row.names(pred.Class_I.LINE) <- row.names(mydata)
pred.Class_I.LINE
colnames(pred.Class_I.LINE) <- c("Class_I.LINE")

set.seed(111111)
model.11.Class_I.LINE <- makeBayouModel(dat.2n ~ Class_I.LINE, rjpars = c(), 
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LINE, SE=0, prior=prior.11.Class_I.LINE, D=D11.Class_I.LINE)
model.N1.Class_I.LINE <- makeBayouModel(dat.2n ~ Class_I.LINE, rjpars = c("theta"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LINE, SE=0, prior=prior.N1.Class_I.LINE, D=DN1.Class_I.LINE)
model.NN.Class_I.LINE <- makeBayouModel(dat.2n ~ Class_I.LINE, rjpars = c("theta", "Class_I.LINE"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LINE, SE=0, prior=prior.NN.Class_I.LINE, D=DNN.Class_I.LINE)

mcmc.11.Class_I.LINE <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LINE, SE=0, model=model.11.Class_I.LINE$model, prior=prior.11.Class_I.LINE, startpar=model.11.Class_I.LINE$startpar, outname="model11_r001_Class_I.LINE", plot.freq=NULL)
mcmc.N1.Class_I.LINE <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LINE, SE=0, model=model.N1.Class_I.LINE$model, prior=prior.N1.Class_I.LINE, startpar=model.N1.Class_I.LINE$startpar, outname="modelN1_r001_Class_I.LINE", plot.freq=NULL)
mcmc.NN.Class_I.LINE <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LINE, SE=0, model=model.NN.Class_I.LINE$model, prior=prior.NN.Class_I.LINE, startpar=model.NN.Class_I.LINE$startpar, outname="modelNN_r001_Class_I.LINE", plot.freq=NULL)

set.seed(1)
mcmc.11.Class_I.LINE$run(1000000)
mcmc.N1.Class_I.LINE$run(1000000)
mcmc.NN.Class_I.LINE$run(1000000)

chain.11.Class_I.LINE <- set.burnin(mcmc.11.Class_I.LINE$load(), 0.3)
chain.N1.Class_I.LINE <- set.burnin(mcmc.N1.Class_I.LINE$load(), 0.3)
chain.NN.Class_I.LINE <- set.burnin(mcmc.NN.Class_I.LINE$load(), 0.3)

shiftsumsN1.Class_I.LINE <- shiftSummaries(chain.N1.Class_I.LINE, mcmc.N1.Class_I.LINE, pp.cutoff=0.17)
shiftsumsNN.Class_I.LINE <- shiftSummaries(chain.NN.Class_I.LINE, mcmc.NN.Class_I.LINE, pp.cutoff=0.3)

plotShiftSummaries(shiftsumsN1.Class_I.LINE, lwd=2, single.plot=TRUE, label.pts=FALSE)
plotShiftSummaries(shiftsumsNN.Class_I.LINE, lwd=2, single.plot=TRUE, label.pts=FALSE)

Bk <- qbeta(seq(0,1, length.out=5), 0.3,1)
set.seed(1)
ss.11.Class_I.LINE <- mcmc.11.Class_I.LINE$steppingstone(10000, chain.11.Class_I.LINE, Bk, burnin=0.3, plot=FALSE)
ss.N1.Class_I.LINE <- mcmc.N1.Class_I.LINE$steppingstone(10000, chain.N1.Class_I.LINE, Bk, burnin=0.3, plot=FALSE)
ss.NN.Class_I.LINE <- mcmc.NN.Class_I.LINE$steppingstone(10000, chain.NN.Class_I.LINE, Bk, burnin=0.3, plot=FALSE)

mlnL.Class_I.LINE <- c("11"=ss.11.Class_I.LINE$lnr, "N1"=ss.N1.Class_I.LINE$lnr, "NN"=ss.NN.Class_I.LINE$lnr)
mlnL.Class_I.LINE


summary.N1.Class_I.LINE <- summary(chain.N1.Class_I.LINE)
#par(mfrow=c(3, 5) )
#plot(chain.NN.Class_I.LINE, auto.layout=FALSE)


#dev.off()
#plotSimmap.mcmc(chain.N1.Class_I.LINE, burnin = 0.3, pp.cutoff = 0.17, cex = 0.5)






#Class_II.Subclass_2.Maverick

prior.11.Class_II.Subclass_2.Maverick <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_II.Subclass_2.Maverick="dnorm",
                                  dsb="fixed", dk="fixed", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_II.Subclass_2.Maverick=list(mean=0.7, sd=0.15),
                                  dtheta=list(mean=0, sd=1)),
                       fixed=list(k=0, sb=numeric(0))
)

prior.N1.Class_II.Subclass_2.Maverick <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_II.Subclass_2.Maverick="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dbeta_Class_II.Subclass_2.Maverick=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50),
                                  dtheta=list(mean=0, sd=1))
)


prior.NN.Class_II.Subclass_2.Maverick <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_II.Subclass_2.Maverick="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_II.Subclass_2.Maverick=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50), 
                                  dtheta=list(mean=0, sd=1))
)


D11.Class_II.Subclass_2.Maverick = list(alpha=2, sig2=2, beta_Class_II.Subclass_2.Maverick=0.1, k=1, theta=0.5, slide=1)
DN1.Class_II.Subclass_2.Maverick = list(alpha=2, sig2=2, beta_Class_II.Subclass_2.Maverick=0.1, k=1, theta=2, slide=1)
DNN.Class_II.Subclass_2.Maverick = list(alpha=2, sig2=2, beta_Class_II.Subclass_2.Maverick=0.3, k=c(1,1), theta=2, slide=1)

pred.Class_II.Subclass_2.Maverick <- as.numeric(mydata[,13])
dim(pred.Class_II.Subclass_2.Maverick) <- c(47,1)
row.names(pred.Class_II.Subclass_2.Maverick) <- row.names(mydata)
pred.Class_II.Subclass_2.Maverick
colnames(pred.Class_II.Subclass_2.Maverick) <- c("Class_II.Subclass_2.Maverick")

set.seed(1111111)
model.11.Class_II.Subclass_2.Maverick <- makeBayouModel(dat.2n ~ Class_II.Subclass_2.Maverick, rjpars = c(), 
                           tree=tree, dat=dat.2n, pred=pred.Class_II.Subclass_2.Maverick, SE=0, prior=prior.11.Class_II.Subclass_2.Maverick, D=D11.Class_II.Subclass_2.Maverick)
model.N1.Class_II.Subclass_2.Maverick <- makeBayouModel(dat.2n ~ Class_II.Subclass_2.Maverick, rjpars = c("theta"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_II.Subclass_2.Maverick, SE=0, prior=prior.N1.Class_II.Subclass_2.Maverick, D=DN1.Class_II.Subclass_2.Maverick)
model.NN.Class_II.Subclass_2.Maverick <- makeBayouModel(dat.2n ~ Class_II.Subclass_2.Maverick, rjpars = c("theta", "Class_II.Subclass_2.Maverick"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_II.Subclass_2.Maverick, SE=0, prior=prior.NN.Class_II.Subclass_2.Maverick, D=DNN.Class_II.Subclass_2.Maverick)

mcmc.11.Class_II.Subclass_2.Maverick <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_II.Subclass_2.Maverick, SE=0, model=model.11.Class_II.Subclass_2.Maverick$model, prior=prior.11.Class_II.Subclass_2.Maverick, startpar=model.11.Class_II.Subclass_2.Maverick$startpar, outname="model11_r001_Class_II.Subclass_2.Maverick", plot.freq=NULL)
mcmc.N1.Class_II.Subclass_2.Maverick <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_II.Subclass_2.Maverick, SE=0, model=model.N1.Class_II.Subclass_2.Maverick$model, prior=prior.N1.Class_II.Subclass_2.Maverick, startpar=model.N1.Class_II.Subclass_2.Maverick$startpar, outname="modelN1_r001_Class_II.Subclass_2.Maverick", plot.freq=NULL)
mcmc.NN.Class_II.Subclass_2.Maverick <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_II.Subclass_2.Maverick, SE=0, model=model.NN.Class_II.Subclass_2.Maverick$model, prior=prior.NN.Class_II.Subclass_2.Maverick, startpar=model.NN.Class_II.Subclass_2.Maverick$startpar, outname="modelNN_r001_Class_II.Subclass_2.Maverick", plot.freq=NULL)

set.seed(1)
mcmc.11.Class_II.Subclass_2.Maverick$run(1000000)
mcmc.N1.Class_II.Subclass_2.Maverick$run(1000000)
mcmc.NN.Class_II.Subclass_2.Maverick$run(1000000)

chain.11.Class_II.Subclass_2.Maverick <- set.burnin(mcmc.11.Class_II.Subclass_2.Maverick$load(), 0.3)
chain.N1.Class_II.Subclass_2.Maverick <- set.burnin(mcmc.N1.Class_II.Subclass_2.Maverick$load(), 0.3)
chain.NN.Class_II.Subclass_2.Maverick <- set.burnin(mcmc.NN.Class_II.Subclass_2.Maverick$load(), 0.3)

shiftsumsN1.Class_II.Subclass_2.Maverick <- shiftSummaries(chain.N1.Class_II.Subclass_2.Maverick, mcmc.N1.Class_II.Subclass_2.Maverick, pp.cutoff=0.17)
shiftsumsNN.Class_II.Subclass_2.Maverick <- shiftSummaries(chain.NN.Class_II.Subclass_2.Maverick, mcmc.NN.Class_II.Subclass_2.Maverick, pp.cutoff=0.3)

plotShiftSummaries(shiftsumsN1.Class_II.Subclass_2.Maverick, lwd=2, single.plot=TRUE, label.pts=FALSE)
plotShiftSummaries(shiftsumsNN.Class_II.Subclass_2.Maverick, lwd=2, single.plot=TRUE, label.pts=FALSE)

Bk <- qbeta(seq(0,1, length.out=5), 0.3,1)
set.seed(1)
ss.11.Class_II.Subclass_2.Maverick <- mcmc.11.Class_II.Subclass_2.Maverick$steppingstone(10000, chain.11.Class_II.Subclass_2.Maverick, Bk, burnin=0.3, plot=FALSE)
ss.N1.Class_II.Subclass_2.Maverick <- mcmc.N1.Class_II.Subclass_2.Maverick$steppingstone(10000, chain.N1.Class_II.Subclass_2.Maverick, Bk, burnin=0.3, plot=FALSE)
ss.NN.Class_II.Subclass_2.Maverick <- mcmc.NN.Class_II.Subclass_2.Maverick$steppingstone(10000, chain.NN.Class_II.Subclass_2.Maverick, Bk, burnin=0.3, plot=FALSE)

mlnL.Class_II.Subclass_2.Maverick <- c("11"=ss.11.Class_II.Subclass_2.Maverick$lnr, "N1"=ss.N1.Class_II.Subclass_2.Maverick$lnr, "NN"=ss.NN.Class_II.Subclass_2.Maverick$lnr)
mlnL.Class_II.Subclass_2.Maverick


summary.N1.Class_II.Subclass_2.Maverick <- summary(chain.N1.Class_II.Subclass_2.Maverick)
#par(mfrow=c(3, 5) )
#plot(chain.NN.Class_II.Subclass_2.Maverick, auto.layout=FALSE)


#dev.off()
#plotSimmap.mcmc(chain.N1.Class_II.Subclass_2.Maverick, burnin = 0.3, pp.cutoff = 0.17, cex = 0.5)



#Class_I.LTR.Bel.Pao

prior.11.Class_I.LTR.Bel.Pao <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LTR.Bel.Pao="dnorm",
                                  dsb="fixed", dk="fixed", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_I.LTR.Bel.Pao=list(mean=0.7, sd=0.15),
                                  dtheta=list(mean=0, sd=1)),
                       fixed=list(k=0, sb=numeric(0))
)

prior.N1.Class_I.LTR.Bel.Pao <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LTR.Bel.Pao="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dbeta_Class_I.LTR.Bel.Pao=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50),
                                  dtheta=list(mean=0, sd=1))
)


prior.NN.Class_I.LTR.Bel.Pao <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LTR.Bel.Pao="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_I.LTR.Bel.Pao=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50), 
                                  dtheta=list(mean=0, sd=1))
)


D11.Class_I.LTR.Bel.Pao = list(alpha=2, sig2=2, beta_Class_I.LTR.Bel.Pao=0.1, k=1, theta=0.5, slide=1)
DN1.Class_I.LTR.Bel.Pao = list(alpha=2, sig2=2, beta_Class_I.LTR.Bel.Pao=0.1, k=1, theta=2, slide=1)
DNN.Class_I.LTR.Bel.Pao = list(alpha=2, sig2=2, beta_Class_I.LTR.Bel.Pao=0.3, k=c(1,1), theta=2, slide=1)

pred.Class_I.LTR.Bel.Pao <- as.numeric(mydata[,8])
dim(pred.Class_I.LTR.Bel.Pao) <- c(47,1)
row.names(pred.Class_I.LTR.Bel.Pao) <- row.names(mydata)
pred.Class_I.LTR.Bel.Pao
colnames(pred.Class_I.LTR.Bel.Pao) <- c("Class_I.LTR.Bel.Pao")

set.seed(1111111)
model.11.Class_I.LTR.Bel.Pao <- makeBayouModel(dat.2n ~ Class_I.LTR.Bel.Pao, rjpars = c(), 
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LTR.Bel.Pao, SE=0, prior=prior.11.Class_I.LTR.Bel.Pao, D=D11.Class_I.LTR.Bel.Pao)
model.N1.Class_I.LTR.Bel.Pao <- makeBayouModel(dat.2n ~ Class_I.LTR.Bel.Pao, rjpars = c("theta"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LTR.Bel.Pao, SE=0, prior=prior.N1.Class_I.LTR.Bel.Pao, D=DN1.Class_I.LTR.Bel.Pao)
model.NN.Class_I.LTR.Bel.Pao <- makeBayouModel(dat.2n ~ Class_I.LTR.Bel.Pao, rjpars = c("theta", "Class_I.LTR.Bel.Pao"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LTR.Bel.Pao, SE=0, prior=prior.NN.Class_I.LTR.Bel.Pao, D=DNN.Class_I.LTR.Bel.Pao)

mcmc.11.Class_I.LTR.Bel.Pao <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LTR.Bel.Pao, SE=0, model=model.11.Class_I.LTR.Bel.Pao$model, prior=prior.11.Class_I.LTR.Bel.Pao, startpar=model.11.Class_I.LTR.Bel.Pao$startpar, outname="model11_r001_Class_I.LTR.Bel.Pao", plot.freq=NULL)
mcmc.N1.Class_I.LTR.Bel.Pao <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LTR.Bel.Pao, SE=0, model=model.N1.Class_I.LTR.Bel.Pao$model, prior=prior.N1.Class_I.LTR.Bel.Pao, startpar=model.N1.Class_I.LTR.Bel.Pao$startpar, outname="modelN1_r001_Class_I.LTR.Bel.Pao", plot.freq=NULL)
mcmc.NN.Class_I.LTR.Bel.Pao <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LTR.Bel.Pao, SE=0, model=model.NN.Class_I.LTR.Bel.Pao$model, prior=prior.NN.Class_I.LTR.Bel.Pao, startpar=model.NN.Class_I.LTR.Bel.Pao$startpar, outname="modelNN_r001_Class_I.LTR.Bel.Pao", plot.freq=NULL)

set.seed(1)
mcmc.11.Class_I.LTR.Bel.Pao$run(1000000)
mcmc.N1.Class_I.LTR.Bel.Pao$run(1000000)
mcmc.NN.Class_I.LTR.Bel.Pao$run(1000000)

chain.11.Class_I.LTR.Bel.Pao <- set.burnin(mcmc.11.Class_I.LTR.Bel.Pao$load(), 0.3)
chain.N1.Class_I.LTR.Bel.Pao <- set.burnin(mcmc.N1.Class_I.LTR.Bel.Pao$load(), 0.3)
chain.NN.Class_I.LTR.Bel.Pao <- set.burnin(mcmc.NN.Class_I.LTR.Bel.Pao$load(), 0.3)

shiftsumsN1.Class_I.LTR.Bel.Pao <- shiftSummaries(chain.N1.Class_I.LTR.Bel.Pao, mcmc.N1.Class_I.LTR.Bel.Pao, pp.cutoff=0.17)
shiftsumsNN.Class_I.LTR.Bel.Pao <- shiftSummaries(chain.NN.Class_I.LTR.Bel.Pao, mcmc.NN.Class_I.LTR.Bel.Pao, pp.cutoff=0.3)

plotShiftSummaries(shiftsumsN1.Class_I.LTR.Bel.Pao, lwd=2, single.plot=TRUE, label.pts=FALSE)
plotShiftSummaries(shiftsumsNN.Class_I.LTR.Bel.Pao, lwd=2, single.plot=TRUE, label.pts=FALSE)

Bk <- qbeta(seq(0,1, length.out=5), 0.3,1)
set.seed(1)
ss.11.Class_I.LTR.Bel.Pao <- mcmc.11.Class_I.LTR.Bel.Pao$steppingstone(10000, chain.11.Class_I.LTR.Bel.Pao, Bk, burnin=0.3, plot=FALSE)
ss.N1.Class_I.LTR.Bel.Pao <- mcmc.N1.Class_I.LTR.Bel.Pao$steppingstone(10000, chain.N1.Class_I.LTR.Bel.Pao, Bk, burnin=0.3, plot=FALSE)
ss.NN.Class_I.LTR.Bel.Pao <- mcmc.NN.Class_I.LTR.Bel.Pao$steppingstone(10000, chain.NN.Class_I.LTR.Bel.Pao, Bk, burnin=0.3, plot=FALSE)

mlnL.Class_I.LTR.Bel.Pao <- c("11"=ss.11.Class_I.LTR.Bel.Pao$lnr, "N1"=ss.N1.Class_I.LTR.Bel.Pao$lnr, "NN"=ss.NN.Class_I.LTR.Bel.Pao$lnr)
mlnL.Class_I.LTR.Bel.Pao


summary.N1.Class_I.LTR.Bel.Pao <- summary(chain.N1.Class_I.LTR.Bel.Pao)
#par(mfrow=c(3, 5) )
#plot(chain.NN.Class_I.LTR.Bel.Pao, auto.layout=FALSE)


#dev.off()
#plotSimmap.mcmc(chain.N1.Class_I.LTR.Bel.Pao, burnin = 0.3, pp.cutoff = 0.17, cex = 0.5)



#Class_I.LTR.Ty1_copia

prior.11.Class_I.LTR.Ty1_copia <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LTR.Ty1_copia="dnorm",
                                  dsb="fixed", dk="fixed", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_I.LTR.Ty1_copia=list(mean=0.7, sd=0.15),
                                  dtheta=list(mean=0, sd=1)),
                       fixed=list(k=0, sb=numeric(0))
)

prior.N1.Class_I.LTR.Ty1_copia <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LTR.Ty1_copia="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dbeta_Class_I.LTR.Ty1_copia=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50),
                                  dtheta=list(mean=0, sd=1))
)


prior.NN.Class_I.LTR.Ty1_copia <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LTR.Ty1_copia="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_I.LTR.Ty1_copia=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50), 
                                  dtheta=list(mean=0, sd=1))
)


D11.Class_I.LTR.Ty1_copia = list(alpha=2, sig2=2, beta_Class_I.LTR.Ty1_copia=0.1, k=1, theta=0.5, slide=1)
DN1.Class_I.LTR.Ty1_copia = list(alpha=2, sig2=2, beta_Class_I.LTR.Ty1_copia=0.1, k=1, theta=2, slide=1)
DNN.Class_I.LTR.Ty1_copia = list(alpha=2, sig2=2, beta_Class_I.LTR.Ty1_copia=0.3, k=c(1,1), theta=2, slide=1)

pred.Class_I.LTR.Ty1_copia <- as.numeric(mydata[,9])
dim(pred.Class_I.LTR.Ty1_copia) <- c(47,1)
row.names(pred.Class_I.LTR.Ty1_copia) <- row.names(mydata)
pred.Class_I.LTR.Ty1_copia
colnames(pred.Class_I.LTR.Ty1_copia) <- c("Class_I.LTR.Ty1_copia")

set.seed(1111111)
model.11.Class_I.LTR.Ty1_copia <- makeBayouModel(dat.2n ~ Class_I.LTR.Ty1_copia, rjpars = c(), 
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LTR.Ty1_copia, SE=0, prior=prior.11.Class_I.LTR.Ty1_copia, D=D11.Class_I.LTR.Ty1_copia)
model.N1.Class_I.LTR.Ty1_copia <- makeBayouModel(dat.2n ~ Class_I.LTR.Ty1_copia, rjpars = c("theta"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LTR.Ty1_copia, SE=0, prior=prior.N1.Class_I.LTR.Ty1_copia, D=DN1.Class_I.LTR.Ty1_copia)
model.NN.Class_I.LTR.Ty1_copia <- makeBayouModel(dat.2n ~ Class_I.LTR.Ty1_copia, rjpars = c("theta", "Class_I.LTR.Ty1_copia"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LTR.Ty1_copia, SE=0, prior=prior.NN.Class_I.LTR.Ty1_copia, D=DNN.Class_I.LTR.Ty1_copia)

mcmc.11.Class_I.LTR.Ty1_copia <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LTR.Ty1_copia, SE=0, model=model.11.Class_I.LTR.Ty1_copia$model, prior=prior.11.Class_I.LTR.Ty1_copia, startpar=model.11.Class_I.LTR.Ty1_copia$startpar, outname="model11_r001_Class_I.LTR.Ty1_copia", plot.freq=NULL)
mcmc.N1.Class_I.LTR.Ty1_copia <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LTR.Ty1_copia, SE=0, model=model.N1.Class_I.LTR.Ty1_copia$model, prior=prior.N1.Class_I.LTR.Ty1_copia, startpar=model.N1.Class_I.LTR.Ty1_copia$startpar, outname="modelN1_r001_Class_I.LTR.Ty1_copia", plot.freq=NULL)
mcmc.NN.Class_I.LTR.Ty1_copia <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LTR.Ty1_copia, SE=0, model=model.NN.Class_I.LTR.Ty1_copia$model, prior=prior.NN.Class_I.LTR.Ty1_copia, startpar=model.NN.Class_I.LTR.Ty1_copia$startpar, outname="modelNN_r001_Class_I.LTR.Ty1_copia", plot.freq=NULL)

set.seed(1)
mcmc.11.Class_I.LTR.Ty1_copia$run(1000000)
mcmc.N1.Class_I.LTR.Ty1_copia$run(1000000)
mcmc.NN.Class_I.LTR.Ty1_copia$run(1000000)

chain.11.Class_I.LTR.Ty1_copia <- set.burnin(mcmc.11.Class_I.LTR.Ty1_copia$load(), 0.3)
chain.N1.Class_I.LTR.Ty1_copia <- set.burnin(mcmc.N1.Class_I.LTR.Ty1_copia$load(), 0.3)
chain.NN.Class_I.LTR.Ty1_copia <- set.burnin(mcmc.NN.Class_I.LTR.Ty1_copia$load(), 0.3)

shiftsumsN1.Class_I.LTR.Ty1_copia <- shiftSummaries(chain.N1.Class_I.LTR.Ty1_copia, mcmc.N1.Class_I.LTR.Ty1_copia, pp.cutoff=0.17)
shiftsumsNN.Class_I.LTR.Ty1_copia <- shiftSummaries(chain.NN.Class_I.LTR.Ty1_copia, mcmc.NN.Class_I.LTR.Ty1_copia, pp.cutoff=0.3)

plotShiftSummaries(shiftsumsN1.Class_I.LTR.Ty1_copia, lwd=2, single.plot=TRUE, label.pts=FALSE)
plotShiftSummaries(shiftsumsNN.Class_I.LTR.Ty1_copia, lwd=2, single.plot=TRUE, label.pts=FALSE)

Bk <- qbeta(seq(0,1, length.out=5), 0.3,1)
set.seed(1)
ss.11.Class_I.LTR.Ty1_copia <- mcmc.11.Class_I.LTR.Ty1_copia$steppingstone(10000, chain.11.Class_I.LTR.Ty1_copia, Bk, burnin=0.3, plot=FALSE)
ss.N1.Class_I.LTR.Ty1_copia <- mcmc.N1.Class_I.LTR.Ty1_copia$steppingstone(10000, chain.N1.Class_I.LTR.Ty1_copia, Bk, burnin=0.3, plot=FALSE)
ss.NN.Class_I.LTR.Ty1_copia <- mcmc.NN.Class_I.LTR.Ty1_copia$steppingstone(10000, chain.NN.Class_I.LTR.Ty1_copia, Bk, burnin=0.3, plot=FALSE)

mlnL.Class_I.LTR.Ty1_copia <- c("11"=ss.11.Class_I.LTR.Ty1_copia$lnr, "N1"=ss.N1.Class_I.LTR.Ty1_copia$lnr, "NN"=ss.NN.Class_I.LTR.Ty1_copia$lnr)
mlnL.Class_I.LTR.Ty1_copia


summary.N1.Class_I.LTR.Ty1_copia <- summary(chain.N1.Class_I.LTR.Ty1_copia)
#par(mfrow=c(3, 5) )
#plot(chain.NN.Class_I.LTR.Ty1_copia, auto.layout=FALSE)


#dev.off()
plotSimmap.mcmc(chain.N1.Class_I.LTR.Ty1_copia, burnin = 0.3, pp.cutoff = 0.17, cex = 0.5)



#Class_I.LTR.Ty3_gypsy

prior.11.Class_I.LTR.Ty3_gypsy <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LTR.Ty3_gypsy="dnorm",
                                  dsb="fixed", dk="fixed", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_I.LTR.Ty3_gypsy=list(mean=0.7, sd=0.15),
                                  dtheta=list(mean=0, sd=1)),
                       fixed=list(k=0, sb=numeric(0))
)

prior.N1.Class_I.LTR.Ty3_gypsy <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LTR.Ty3_gypsy="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dbeta_Class_I.LTR.Ty3_gypsy=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50),
                                  dtheta=list(mean=0, sd=1))
)


prior.NN.Class_I.LTR.Ty3_gypsy <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_Class_I.LTR.Ty3_gypsy="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_Class_I.LTR.Ty3_gypsy=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50), 
                                  dtheta=list(mean=0, sd=1))
)


D11.Class_I.LTR.Ty3_gypsy = list(alpha=2, sig2=2, beta_Class_I.LTR.Ty3_gypsy=0.1, k=1, theta=0.5, slide=1)
DN1.Class_I.LTR.Ty3_gypsy = list(alpha=2, sig2=2, beta_Class_I.LTR.Ty3_gypsy=0.1, k=1, theta=2, slide=1)
DNN.Class_I.LTR.Ty3_gypsy = list(alpha=2, sig2=2, beta_Class_I.LTR.Ty3_gypsy=0.3, k=c(1,1), theta=2, slide=1)

pred.Class_I.LTR.Ty3_gypsy <- as.numeric(mydata[,10])
dim(pred.Class_I.LTR.Ty3_gypsy) <- c(47,1)
row.names(pred.Class_I.LTR.Ty3_gypsy) <- row.names(mydata)
pred.Class_I.LTR.Ty3_gypsy
colnames(pred.Class_I.LTR.Ty3_gypsy) <- c("Class_I.LTR.Ty3_gypsy")

set.seed(1111111)
model.11.Class_I.LTR.Ty3_gypsy <- makeBayouModel(dat.2n ~ Class_I.LTR.Ty3_gypsy, rjpars = c(), 
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LTR.Ty3_gypsy, SE=0, prior=prior.11.Class_I.LTR.Ty3_gypsy, D=D11.Class_I.LTR.Ty3_gypsy)
model.N1.Class_I.LTR.Ty3_gypsy <- makeBayouModel(dat.2n ~ Class_I.LTR.Ty3_gypsy, rjpars = c("theta"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LTR.Ty3_gypsy, SE=0, prior=prior.N1.Class_I.LTR.Ty3_gypsy, D=DN1.Class_I.LTR.Ty3_gypsy)
model.NN.Class_I.LTR.Ty3_gypsy <- makeBayouModel(dat.2n ~ Class_I.LTR.Ty3_gypsy, rjpars = c("theta", "Class_I.LTR.Ty3_gypsy"),  
                           tree=tree, dat=dat.2n, pred=pred.Class_I.LTR.Ty3_gypsy, SE=0, prior=prior.NN.Class_I.LTR.Ty3_gypsy, D=DNN.Class_I.LTR.Ty3_gypsy)

mcmc.11.Class_I.LTR.Ty3_gypsy <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LTR.Ty3_gypsy, SE=0, model=model.11.Class_I.LTR.Ty3_gypsy$model, prior=prior.11.Class_I.LTR.Ty3_gypsy, startpar=model.11.Class_I.LTR.Ty3_gypsy$startpar, outname="model11_r001_Class_I.LTR.Ty3_gypsy", plot.freq=NULL)
mcmc.N1.Class_I.LTR.Ty3_gypsy <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LTR.Ty3_gypsy, SE=0, model=model.N1.Class_I.LTR.Ty3_gypsy$model, prior=prior.N1.Class_I.LTR.Ty3_gypsy, startpar=model.N1.Class_I.LTR.Ty3_gypsy$startpar, outname="modelN1_r001_Class_I.LTR.Ty3_gypsy", plot.freq=NULL)
mcmc.NN.Class_I.LTR.Ty3_gypsy <- bayou.makeMCMC(tree, dat.2n, pred=pred.Class_I.LTR.Ty3_gypsy, SE=0, model=model.NN.Class_I.LTR.Ty3_gypsy$model, prior=prior.NN.Class_I.LTR.Ty3_gypsy, startpar=model.NN.Class_I.LTR.Ty3_gypsy$startpar, outname="modelNN_r001_Class_I.LTR.Ty3_gypsy", plot.freq=NULL)

set.seed(1)
mcmc.11.Class_I.LTR.Ty3_gypsy$run(1000000)
mcmc.N1.Class_I.LTR.Ty3_gypsy$run(1000000)
mcmc.NN.Class_I.LTR.Ty3_gypsy$run(1000000)

chain.11.Class_I.LTR.Ty3_gypsy <- set.burnin(mcmc.11.Class_I.LTR.Ty3_gypsy$load(), 0.3)
chain.N1.Class_I.LTR.Ty3_gypsy <- set.burnin(mcmc.N1.Class_I.LTR.Ty3_gypsy$load(), 0.3)
chain.NN.Class_I.LTR.Ty3_gypsy <- set.burnin(mcmc.NN.Class_I.LTR.Ty3_gypsy$load(), 0.3)

shiftsumsN1.Class_I.LTR.Ty3_gypsy <- shiftSummaries(chain.N1.Class_I.LTR.Ty3_gypsy, mcmc.N1.Class_I.LTR.Ty3_gypsy, pp.cutoff=0.17)
shiftsumsNN.Class_I.LTR.Ty3_gypsy <- shiftSummaries(chain.NN.Class_I.LTR.Ty3_gypsy, mcmc.NN.Class_I.LTR.Ty3_gypsy, pp.cutoff=0.3)

plotShiftSummaries(shiftsumsN1.Class_I.LTR.Ty3_gypsy, lwd=2, single.plot=TRUE, label.pts=FALSE)
plotShiftSummaries(shiftsumsNN.Class_I.LTR.Ty3_gypsy, lwd=2, single.plot=TRUE, label.pts=FALSE)

Bk <- qbeta(seq(0,1, length.out=5), 0.3,1)
set.seed(1)
ss.11.Class_I.LTR.Ty3_gypsy <- mcmc.11.Class_I.LTR.Ty3_gypsy$steppingstone(10000, chain.11.Class_I.LTR.Ty3_gypsy, Bk, burnin=0.3, plot=FALSE)
ss.N1.Class_I.LTR.Ty3_gypsy <- mcmc.N1.Class_I.LTR.Ty3_gypsy$steppingstone(10000, chain.N1.Class_I.LTR.Ty3_gypsy, Bk, burnin=0.3, plot=FALSE)
ss.NN.Class_I.LTR.Ty3_gypsy <- mcmc.NN.Class_I.LTR.Ty3_gypsy$steppingstone(10000, chain.NN.Class_I.LTR.Ty3_gypsy, Bk, burnin=0.3, plot=FALSE)

mlnL.Class_I.LTR.Ty3_gypsy <- c("11"=ss.11.Class_I.LTR.Ty3_gypsy$lnr, "N1"=ss.N1.Class_I.LTR.Ty3_gypsy$lnr, "NN"=ss.NN.Class_I.LTR.Ty3_gypsy$lnr)
mlnL.Class_I.LTR.Ty3_gypsy


summary.N1.Class_I.LTR.Ty3_gypsy <- summary(chain.N1.Class_I.LTR.Ty3_gypsy)
#par(mfrow=c(3, 5) )
#plot(chain.NN.Class_I.LTR.Ty3_gypsy, auto.layout=FALSE)


#dev.off()
plotSimmap.mcmc(chain.N1.Class_I.LTR.Ty3_gypsy, burnin = 0.3, pp.cutoff = 0.17, cex = 0.5)




#lass_I.Penelope

prior.11.lass_I.Penelope <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_lass_I.Penelope="dnorm",
                                  dsb="fixed", dk="fixed", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_lass_I.Penelope=list(mean=0.7, sd=0.15),
                                  dtheta=list(mean=0, sd=1)),
                       fixed=list(k=0, sb=numeric(0))
)

prior.N1.lass_I.Penelope <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_lass_I.Penelope="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dbeta_lass_I.Penelope=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50),
                                  dtheta=list(mean=0, sd=1))
)


prior.NN.lass_I.Penelope <- make.prior(tree, plot.prior = FALSE, 
                       dists=list(dalpha="dhalfcauchy", dsig2="dhalfcauchy", dbeta_lass_I.Penelope="dnorm",
                                  dsb="dsb", dk="cdpois", dtheta="dnorm"), 
                       param=list(dalpha=list(scale=0.1), dsig2=list(scale=0.1),
                                  dbeta_lass_I.Penelope=list(mean=0.7, sd=0.15),
                                  dk=list(lambda=10, kmax=50), 
                                  dtheta=list(mean=0, sd=1))
)


D11.lass_I.Penelope = list(alpha=2, sig2=2, beta_lass_I.Penelope=0.1, k=1, theta=0.5, slide=1)
DN1.lass_I.Penelope = list(alpha=2, sig2=2, beta_lass_I.Penelope=0.1, k=1, theta=2, slide=1)
DNN.lass_I.Penelope = list(alpha=2, sig2=2, beta_lass_I.Penelope=0.3, k=c(1,1), theta=2, slide=1)

pred.lass_I.Penelope <- as.numeric(mydata[,11])
dim(pred.lass_I.Penelope) <- c(47,1)
row.names(pred.lass_I.Penelope) <- row.names(mydata)
pred.lass_I.Penelope
colnames(pred.lass_I.Penelope) <- c("lass_I.Penelope")

set.seed(1111111)
model.11.lass_I.Penelope <- makeBayouModel(dat.2n ~ lass_I.Penelope, rjpars = c(), 
                           tree=tree, dat=dat.2n, pred=pred.lass_I.Penelope, SE=0, prior=prior.11.lass_I.Penelope, D=D11.lass_I.Penelope)
model.N1.lass_I.Penelope <- makeBayouModel(dat.2n ~ lass_I.Penelope, rjpars = c("theta"),  
                           tree=tree, dat=dat.2n, pred=pred.lass_I.Penelope, SE=0, prior=prior.N1.lass_I.Penelope, D=DN1.lass_I.Penelope)
model.NN.lass_I.Penelope <- makeBayouModel(dat.2n ~ lass_I.Penelope, rjpars = c("theta", "lass_I.Penelope"),  
                           tree=tree, dat=dat.2n, pred=pred.lass_I.Penelope, SE=0, prior=prior.NN.lass_I.Penelope, D=DNN.lass_I.Penelope)

mcmc.11.lass_I.Penelope <- bayou.makeMCMC(tree, dat.2n, pred=pred.lass_I.Penelope, SE=0, model=model.11.lass_I.Penelope$model, prior=prior.11.lass_I.Penelope, startpar=model.11.lass_I.Penelope$startpar, outname="model11_r001_lass_I.Penelope", plot.freq=NULL)
mcmc.N1.lass_I.Penelope <- bayou.makeMCMC(tree, dat.2n, pred=pred.lass_I.Penelope, SE=0, model=model.N1.lass_I.Penelope$model, prior=prior.N1.lass_I.Penelope, startpar=model.N1.lass_I.Penelope$startpar, outname="modelN1_r001_lass_I.Penelope", plot.freq=NULL)
mcmc.NN.lass_I.Penelope <- bayou.makeMCMC(tree, dat.2n, pred=pred.lass_I.Penelope, SE=0, model=model.NN.lass_I.Penelope$model, prior=prior.NN.lass_I.Penelope, startpar=model.NN.lass_I.Penelope$startpar, outname="modelNN_r001_lass_I.Penelope", plot.freq=NULL)

set.seed(1)
mcmc.11.lass_I.Penelope$run(1000000)
mcmc.N1.lass_I.Penelope$run(1000000)
mcmc.NN.lass_I.Penelope$run(1000000)

chain.11.lass_I.Penelope <- set.burnin(mcmc.11.lass_I.Penelope$load(), 0.3)
chain.N1.lass_I.Penelope <- set.burnin(mcmc.N1.lass_I.Penelope$load(), 0.3)
chain.NN.lass_I.Penelope <- set.burnin(mcmc.NN.lass_I.Penelope$load(), 0.3)

shiftsumsN1.lass_I.Penelope <- shiftSummaries(chain.N1.lass_I.Penelope, mcmc.N1.lass_I.Penelope, pp.cutoff=0.17)
shiftsumsNN.lass_I.Penelope <- shiftSummaries(chain.NN.lass_I.Penelope, mcmc.NN.lass_I.Penelope, pp.cutoff=0.3)

plotShiftSummaries(shiftsumsN1.lass_I.Penelope, lwd=2, single.plot=TRUE, label.pts=FALSE)
plotShiftSummaries(shiftsumsNN.lass_I.Penelope, lwd=2, single.plot=TRUE, label.pts=FALSE)

Bk <- qbeta(seq(0,1, length.out=5), 0.3,1)
set.seed(1)
ss.11.lass_I.Penelope <- mcmc.11.lass_I.Penelope$steppingstone(10000, chain.11.lass_I.Penelope, Bk, burnin=0.3, plot=FALSE)
ss.N1.lass_I.Penelope <- mcmc.N1.lass_I.Penelope$steppingstone(10000, chain.N1.lass_I.Penelope, Bk, burnin=0.3, plot=FALSE)
ss.NN.lass_I.Penelope <- mcmc.NN.lass_I.Penelope$steppingstone(10000, chain.NN.lass_I.Penelope, Bk, burnin=0.3, plot=FALSE)

mlnL.lass_I.Penelope <- c("11"=ss.11.lass_I.Penelope$lnr, "N1"=ss.N1.lass_I.Penelope$lnr, "NN"=ss.NN.lass_I.Penelope$lnr)
mlnL.lass_I.Penelope


summary.N1.lass_I.Penelope <- summary(chain.N1.lass_I.Penelope)
#par(mfrow=c(3, 5) )
#plot(chain.NN.lass_I.Penelope, auto.layout=FALSE)


#dev.off()
plotSimmap.mcmc(chain.N1.Class_I.LTR.Ty3_gypsy, burnin = 0.3, pp.cutoff = 0.17, cex = 0.5)

```

```{r}
library(slouch)
mydata2 <- mydata
mydata2<- mydata2[tree$tip.label,]


model0 <- slouch.fit(phy = tree, species = mydata2$species, response = mydata2$Chromosome_2N)

summary(model0)

model1 <- slouch.fit(phy = tree, species = mydata2$species, response = mydata2$Chromosome_2N, random.cov = mydata2$All.repeat.mobile_element.Class_I.DIRS)

summary(model1)

model2 <- slouch.fit(phy = tree, species = mydata2$species, response = mydata2$Chromosome_2N, random.cov = mydata2$All.repeat.mobile_element.Class_I.LINE)

summary(model2)

model3 <- slouch.fit(phy = tree, species = mydata2$species, response = mydata2$Chromosome_2N, random.cov = mydata2$All.repeat.mobile_element.Class_I.LTR)

summary(model3)


model4 <- slouch.fit(phy = tree, species = mydata2$species, response = mydata2$Chromosome_2N, random.cov = mydata2$All.repeat.mobile_element.Class_I.LTR.Bel.Pao)

summary(model4)

model5 <- slouch.fit(phy = tree, species = mydata2$species, response = mydata2$Chromosome_2N, random.cov = mydata2$All.repeat.mobile_element.Class_I.LTR.Ty1_copia)

summary(model5)

model6 <- slouch.fit(phy = tree, species = mydata2$species, response = mydata2$Chromosome_2N, random.cov = mydata2$All.repeat.mobile_element.Class_I.LTR.Ty3_gypsy)

summary(model6)


model7 <- slouch.fit(phy = tree, species = mydata2$species, response = mydata2$Chromosome_2N, random.cov = mydata2$All.repeat.mobile_element.Class_I.Penelope)

summary(model7)


model8 <- slouch.fit(phy = tree, species = mydata2$species, response = mydata2$Chromosome_2N, random.cov = mydata2$All.repeat.mobile_element.Class_II.Subclass_2.Helitron)

summary(model8)

model9 <- slouch.fit(phy = tree, species = mydata2$species, response = mydata2$Chromosome_2N, random.cov = mydata2$All.repeat.mobile_element.Class_II.Subclass_2.Maverick)

summary(model9)

model10 <- slouch.fit(phy = tree, species = mydata2$species, response = mydata2$Chromosome_2N, random.cov = mydata2$All.repeat.rDNA.45S_rDNA)

summary(model10)

model11 <- slouch.fit(phy = tree, species = mydata2$species, response = mydata2$Chromosome_2N, random.cov = mydata2$All.repeat.satellite)

summary(model11)

```

